### ISSUE TITLE
Spy Satellite Uplink should reveal (complete) map

### ISSUE THREAD

**Issue by francoism90** [phrohdoh/OpenRA#10]
Tried to edit the rules (allied-structures.yaml), but it didn't work unfortunately.
I assume RevealsShroud - Range should be in HEX?

Thanks :)

**Comment by phrohdoh** [comment]
`RevealsShroud` (and all other trait properties that are `WDist`) works like so:

`12c0`, for example, equates to 12 full cells.
`8c256` is 8.25 cells because 1024 / 256 is 1/4th and each cell (in every mod regardless of pixel-size of the artwork) is made up of 1024 world units.

As a response to the title yes it should reveal the entire map but not by using `RevealsShroud` there are other (better) mechanisms in place to deal with this, but they are currently not suited for RA2.

@abcdefg30 plans to fix that when he has time :)

**Comment by GraionDilach** [comment]
A footnote: under the cell unit of measurement, OpenRA takes a cell's diagonal while Westwood means a side. This means every range needs to be recalculated from RA2 to OpenRA.

**Comment by phrohdoh** [comment]
@abcdefg30, any progress on the spy sat (and superweapon logic refactor) logic?

Sorry I have been so busy I haven't taken the time to do it myself.

**Comment by abcdefg30** [comment]
> @abcdefg30, any progress on the spy sat (and superweapon logic refactor) logic?

I unfortunately didn't work on it in the last months ([very WIP branch](https://github.com/OpenRA/OpenRA/compare/bleed...abcdefg30:supportoverlay)).
