### ISSUE TITLE
Poor shroud boundaries are noticeable in Dustbowl.

### ISSUE THREAD

**Issue by phrohdoh** [phrohdoh/OpenRA#24]
The southmost oil derrick in the Dustbowl map is too far south and is half cut off by the boundary shroud. Alternatively, the boundary is too far north.
https://github.com/OpenRA/OpenRA/issues/9806

**Comment by GraionDilach** [comment]
All maps converted via the utility have a bigger bottom border than what they had in the source game from what I seen.

**Comment by Mailaender** [comment]
I think you just need to re-import Dustbowl with a current version of the map importer. That will also fix https://github.com/OpenRA/OpenRA/issues/9805. Try my https://github.com/Mailaender/OpenRA/tree/ts-map-import branch.

**Comment by GraionDilach** [comment]
It won't fix https://github.com/OpenRA/OpenRA/issues/9805 I fear.

Many RA2 maps have a bug which modders call "third ore bug". TS allowed four tiberium types in (green, blue, orange and purple, not sure on the last one's color) and while the fourth was bugged (couldn't grow at all) the third was completely functional albeit unused (although some mappers preferred to use it as a tiberium worthing double of the blue tib).

In the early stage of RA2 development, the developers decided to change the two unused tiberiums' artwork/properties to the same artwork/properties the first tiberium used - rendering green, orange and purple tiberium looking and acting the same in their editor (excluding the fact that technically they still were different and the drills were still hardcoded to drill green tiberium). The mapping team ultimately screwed this up and many maps ultimately got shipped which had all the ore on them internally as "orange tiberium" instead of the proper green tiberium. i'm not certain if Dustbowl is among these maps but DEFCON-6 and A Path Beyond II are definitely among these.

I probably have a list in my PC lying around which lists all maps (note, this was never fixed between YR and RA2) affected.

**Comment by Mailaender** [comment]
https://github.com/OpenRA/OpenRA/pull/10397/ now finally will spit out correct map boundaries. It will translate the third resource into the second so maps using the third ore will have gems there instead.

**Comment by Mailaender** [comment]
Fixed in https://github.com/OpenRA/ra2/pull/203.
